---
# tasks file for osh-worker-role

# Swap is required for packages with high resource consumption. For example, webkitgtk.
- name: Create swap partition
  # TODO: Add a check to verify we are on AWS.
  community.general.filesystem:
    fstype: swap
    # TODO: This path should be kept in a variable, as it may vary across clouds.
    dev: /dev/nvme1n1

- name: Mount swap partition
  # TODO: Add a check to verify we are on AWS.
  # `ansible.posix.mount` does not support swap fstype.
  # https://github.com/ansible/ansible/issues/29647
  ansible.builtin.shell: swapon /dev/nvme1n1

- name: Enable SELinux
  ansible.posix.selinux:
    policy: targeted
    state: enforcing

- name: "Update to latest packages"
  ansible.builtin.dnf:
    name: '*'
    state: latest

- name: Install epel
  yum:
    name: "epel-release"
    state: latest
    disable_gpg_check: true

# dnf copr enable @openscanhub/devel
- name: Enable openscanhub copr repository
  community.general.copr:
     name: "@openscanhub/{{ env }}"

# dnf copr enable @codescan/csutils
# This installs the development version of csmock and related packages
- name: Enable csutils copr repository
  community.general.copr:
     name: "@codescan/csutils"

- name: Install osh-worker package
  ansible.builtin.dnf:
    name: osh-worker
    state: latest

# Tasks are run as csmock user
- name: Add csmock group
  ansible.builtin.group:
    name: csmock
    state: present

# csmock user needs root privilleges as it runs mock in the background.
- name: Add csmock user to root group
  ansible.builtin.user:
    name: csmock
    group: csmock
    append: true
    groups: root,mock

# This is required for `/etc/koji.conf.d/stream.conf`.
- name: Install centpkg package
  ansible.builtin.dnf:
    name: centpkg
    state: latest

# This is required for `find-unicode-control`
- name: Install csmock-plugin-unicontrol package
  ansible.builtin.dnf:
    name: csmock-plugin-unicontrol
    state: latest

# This is required for `clippy`
- name: Install csmock-plugin-clippy package
  ansible.builtin.dnf:
    name: csmock-plugin-clippy
    state: latest

# This is required for `pylint`
- name: Install csmock-plugin-pylint package
  ansible.builtin.dnf:
    name: csmock-plugin-pylint
    state: latest

# This is required for `smatch`
- name: Install csmock-plugin-smatch package
  ansible.builtin.dnf:
    name: csmock-plugin-smatch
    state: latest

# Workaround for https://lists.fedoraproject.org/archives/list/openscanhub@lists.fedoraproject.org/thread/GY2XQBNNDHR5VHGA24MBAUBKNAJPUDZW/
# TODO: Remove when latest gcc is released
- name: Copy /etc/mock/fedora-rawhide-gcc-latest-x86_64.cfg
  ansible.builtin.copy:
    src: fedora-rawhide-gcc-latest-x86_64.cfg
    dest: /etc/mock/fedora-rawhide-gcc-latest-x86_64.cfg
    owner: root
    group: mock
    mode: 0644

# Beging Hack
# This is a hack to install known-false-positives from a RPM.
# It should be removed when https://github.com/csutils/csmock/issues/201 is resolved.

- name: Clone known false positives git repository
  ansible.builtin.git:
    repo: 'https://github.com/openscanhub/known-false-positives.git'
    dest: /tmp/known-false-positives

# It is required to build the RPM
- name: Install csdiff package
  ansible.builtin.dnf:
    name: csdiff
    state: latest

- name: Build and install the known-false-positives RPM
  ansible.builtin.shell:
    chdir: /tmp/known-false-positives
    cmd: './make-rpm.sh && dnf install -y ~/rpmbuild/RPMS/noarch/known-false-positives-*.noarch.rpm'

# End Hack

- name: Print status of the worker
  ansible.builtin.debug:
    msg: Worker virtual machine is set up, but `osh-worker` is not started. It should be started by `osh-worker-manager` from osh-hub.
