# https://github.com/sclorg/build-and-push-action
name: Build and push to quay.io registry
on:
  push:
    branches:
      - main
jobs:
  build-and-push-osh-hub:
    runs-on: ubuntu-20.04
    steps:
      - name: Build and push to quay.io registry
        uses: sclorg/build-and-push-action@v4
        with:
          registry: "quay.io"
          registry_namespace: "openscanhub-fedora-infra"
          registry_username: ${{ secrets.REGISTRY_LOGIN }}
          registry_token: ${{ secrets.REGISTRY_TOKEN }}
          dockerfile: "containers/hub.Containerfile"
          docker_context: "containers"
          image_name: "fedora-osh-hub"
          tag: "staging"
  build-and-push-resalloc-server:
    runs-on: ubuntu-20.04
    steps:
      - name: Build and push to quay.io registry
        uses: sclorg/build-and-push-action@v4
        with:
          registry: "quay.io"
          registry_namespace: "openscanhub-fedora-infra"
          registry_username: ${{ secrets.REGISTRY_LOGIN }}
          registry_token: ${{ secrets.REGISTRY_TOKEN }}
          dockerfile: "containers/resalloc-server.Containerfile"
          docker_context: "containers"
          image_name: "resalloc-server"
          tag: "staging"
